### ISSUE TITLE
Support for categorical values

### ISSUE THREAD

**Issue by onetonfoot** [JuliaData/JSONTables.jl#16]
It would be nice to have support for `CategoricalValue` out of the box since they're commonly used in DataFrames now.
It's only a one liner to add but could throw someone not that familiar with the julia data ecosystem.

```julia
StructType(::Type{CategoricalValue{String, T}}) where T = StructTypes.StringType()
```

**Comment by quinnj** [comment]
You can follow progress on this here: https://github.com/JuliaData/CategoricalArrays.jl/pull/276
